AS := nasm
CC := gcc
LD := ld

OUTBIN := out.bin


# -f elf   outfile format is elf_i386
A_FLAG := -f elf

AS_INCLUDE := boot.inc
AS_DEBUG_FLAG += -g

# --------------------
# C options
# -c   do not link
# -m32 outfile format is elf_i386
# -lc  link with libc
# -fno-stack-protector Do not check stack at gcc stage instead of ld
# -fno-builtin
C_WARNG += -Wstrict-prototypes 
C_WARNG += -Wmissing-prototypes
C_WARNG += -Wextra
C_WARNG += -Wall
C_OUT_FMT += -m32
C_FNO_FLAG += -fno-stack-protector 
C_FNO_FLAG += -fno-builtin
C_NO_LINK += -c
C_NO_GOT += -fno-pie
C_DEBUG := -g
# C_ASAN += -fsanitize=address
C_ASAN +=

# C_OPTIM += -O1
# C_OPTIM += -Og
C_OPTIM += -O0
# generate files that encode make rules for the .h dependencies
# more -M* things please `man gcc`
# -MT: Name of the target
# -MMD: List user header files
# -MD : list all header files include system header files
# -MP : add phony targets
# -MF : Name of the file
DEPDIR=$(abs-src)/.deps
DEPFLAGS=-MMD -MF

-include $(DEPDIR)/*.d

abs-src := /home/zm/Development/C/Frog/src/core

# this variable is for choosing target arch, like arm, x86 etc..
ARCH_CUR := x86
PLTF_CUR := pc
# all include dirs
# Main include header files
INCLUDES += $(abs-src)/include
# Arch include header files
INCLUDES += $(abs-src)/arch/$(ARCH_CUR)/include
# Platform include header files
INCLUDES += $(abs-src)/arch/$(PLTF_CUR)/include

BUILD := ..
BUILD_DIR = $(abs-src)/build

#gcc compile time Macro
MACRO_DEBUG := CONFIG_DEBUG
C_DMACRO := -D$(MACRO_DEBUG)

C_OPT := $(C_NO_LINK) $(C_NO_GOT) $(C_WARNG) $(C_OUT_FMT) $(C_FNO_FLAG) $(C_DEBUG) $(C_OPTIM) $(C_ASAN)
C_FLAG := $(C_OPT) $(C_DMACRO) $(foreach D, $(INCLUDES), -I$(D)) $(DEPFLAGS)


# ld things 
#
# -s strip-all Omit all symbol information from the output file.
# -m Emulate the mulation linker. You can list the available emulations
#    with the --verbose or -V options.
#         GNU ld (GNU Binutils for Ubuntu) 2.38
#             Supported emulations:
#              elf_x86_64 elf32_x86_64 elf_i386 elf_iamcu elf_l1om
#              elf_k1om i386pep i386pe
# -lc link libc use dynamic linking
# -Ttext set start virtual address
# -M print a map
CORE_VADDR := 0xc0070000
LD_FLAG := -s -m elf_i386 -Ttext $(CORE_VADDR) 
LD_DEBUG_FLAG := -M -m elf_i386 -T ./scripts/kernel_dbg.ld

