#ifndef _UAPI_FROG_TEST_H
#define _UAPI_FROG_TEST_H

enum frog_test_case_id {
        FROG_TEST_PROCESS_FORK_PARENT_RESULT = 1,
        FROG_TEST_PROCESS_WAIT_PID = 2,
        FROG_TEST_PROCESS_WAIT_STATUS = 3,
        FROG_TEST_PROCESS_FORK_ADDRESS_SPACE = 4,
        FROG_TEST_PROCESS_WAIT_NO_CHILD = 5,
        FROG_TEST_FD_FORK_CHILD_CLOSE = 6,
        FROG_TEST_FD_FORK_PARENT_CLOSE = 7,
        FROG_TEST_SYSCALL_OUT_OF_RANGE = 8,
        FROG_TEST_SYSCALL_UNIMPLEMENTED = 9,
};

#endif
