#ifndef _UAPI_FROG_TEST_H
#define _UAPI_FROG_TEST_H

enum frog_test_case_id {
        FROG_TEST_PROCESS_FORK_PARENT_RESULT = 1,
        FROG_TEST_PROCESS_WAIT_PID = 2,
        FROG_TEST_PROCESS_WAIT_STATUS = 3,
        FROG_TEST_PROCESS_FORK_ADDRESS_SPACE = 4,
        FROG_TEST_PROCESS_WAIT_NO_CHILD = 5,
        FROG_TEST_FD_FORK_CHILD_CLOSE = 6,
        FROG_TEST_FD_FORK_PARENT_CLOSE = 7,
        FROG_TEST_SYSCALL_OUT_OF_RANGE = 8,
        FROG_TEST_SYSCALL_UNIMPLEMENTED = 9,
        FROG_TEST_VM_USER_ADDRESS = 10,
        FROG_TEST_VM_USER_READ = 11,
        FROG_TEST_VM_USER_WRITE = 12,
        FROG_TEST_VM_CLEANUP = 13,
        FROG_TEST_VM_FORK_ROLLBACK = 14,
        FROG_TEST_VM_FORK_SHARED = 15,
        FROG_TEST_VM_EXIT_CHILD_FIRST = 16,
        FROG_TEST_VM_EXIT_PARENT_FIRST = 17,
        FROG_TEST_VM_POST_UNMAP_FAULT = 18,
        FROG_TEST_VM_MMAP_POINTER = 19,
        FROG_TEST_VM_MMAP_ARGUMENTS = 20,
        FROG_TEST_VM_MMAP_FD = 21,
        FROG_TEST_VM_MMAP_ACCESS = 22,
        FROG_TEST_VM_MMAP_UNSUPPORTED = 23,
        FROG_TEST_VM_MUNMAP_EXACT = 24,
        FROG_TEST_VM_FILE_AFTER_CLOSE = 25,
        FROG_TEST_VM_MMAP_BUSY = 26,
};

#define FROG_TEST_VM_PREPARE        0x564d0001U
#define FROG_TEST_VM_VERIFY_CLEANUP 0x564d0002U
#define FROG_TEST_VM_FORK_FAIL_BASE 0x564d0100U
#define FROG_TEST_VM_FORK_FAIL_COUNT 6U
#define FROG_TEST_VM_VERIFY_REFS_BASE 0x564d0200U
#define FROG_TEST_VM_EXPECTED_ADDR  0x40000000U
#define FROG_TEST_VM_LENGTH         (3U * 4096U)
#define FROG_TEST_VM_SEED           0x5aU
#define FROG_TEST_VM_WRITTEN        0xa5U

#endif
